### ISSUE TITLE
Suggestion: geos

### ISSUE THREAD

**Issue by grantmcdermott** [SebKrantz/fastverse#46]
https://paleolimbot.github.io/geos/index.html

To go with the other Spatial (SP) packages. Wraps the underlying `GEOS` C API and only has two recursive dependencies  (`libgeos` and `wk`).

I have some examples showing integration with `data.table` and some benchmarks here: https://grantmcdermott.com/fast-geospatial-datatable-geos/#speeding-things-up-with-geos

**Comment by SebKrantz** [comment]
Thanks! Would you like to propose a one-liner describing geos and linking to CRAN and perhaps a main resource (as you see for the other suggested packages)? That would just save me some time getting into a package I don't really know yet to be able to describe it in one sentence.

**Comment by grantmcdermott** [comment]
Ugh, sorry @SebKrantz I completely dropped the ball on this. Too many things on the go...

**Comment by SebKrantz** [comment]
No problem!
